### PR TITLE
Add function to copy payload text to clipboard

### PR DESCRIPTION
**Pull request by hansonryne**
Just thought this might make it a little easier to use.  It would probably be even better to use toasts or something to alert that the copy was successful, but I don't want to add a bunch of dependencies if you don't want them.

I also left a comment in to either highlight the copied text or not.  Right now it doesn't but it might be your preference to change that.

### CODE REVIEW

**Comment by rastating** [comment]
Thanks for the PR! This was something I was thinking about which some how slipped under the radar. I agree that a toast notification will be a good idea too.

I think the copy would be better done with a button click though. Probably one in the title pane of the payload panel. That way if anyone wants to highlight and copy out a specific part of the payload, they'd be able to.

I'll definitely be merging this in later in the week and seeing what I can do with binding it to work with a button instead though. If you want to add the toasts in the meantime (or try to get the copying working outside the component), feel free to push more to this PR :smile: 

I also was not aware of the `ref` attribute - very handy function for edge cases like this. In the past I've ended up using class selectors with the `document` object; using `ref` is way cleaner; will definitely use this going forward :+1:

**Comment by hansonryne** [comment]
Awesome.  I'll keep working on it when I can.  I really like the project so thanks for opening it up.

**Comment by hansonryne** [comment]
I pushed a couple changes to get the copy function working from a button in the parent panel and integrating toasts to show a successful copy. 

The toasts are not based on any logic that the copy actually happened....they are just going after the copy function runs.  So if it doesn't actually copy the payload for whatever reason, I guess it will lie to the user.  😄 

Hope that helps.  Let me know if I can help any other way.  I might start look at adding some fun payloads as well.

**Comment by rastating** [comment]
Sweet! Will test it out in a few days and get it merged in :smiley:

**Comment by rastating** [comment]
Merged in and deployed :tada: 

I made a few cosmetic alterations to keep the style consistent with the rest of the app (used a FontAwesome icon and altered the colours of the toast). I replaced the `ref` usages with the way it's demonstrated in the React documentation too - I felt this reads a bit easier: https://reactjs.org/docs/refs-and-the-dom.html

Thanks again for the PR - definitely a useful one :smiley:

**Pull request merged**
